name: brymic
favicon: null
layout_spectrum: 0.5561542110517621
typography_spectrum: 0.7911652598995715
title: 'Michael Bryant – Film & Digital Media '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#343434'
    - '#acacac'
    - '#f2f2f2'
    - '#d83a34'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.7544255247339606
  rhythmicContrast: 0.8289191683288664
purpose: []
