name: brymic
favicon: null
layout_spectrum: 0.5561542110517621
typography_spectrum: 0.7911652598995715
title: 'Michael Bryant – Digital Media '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#2e4020'
    - '#496334'
    - '#f8f8f8'
    - '#acada7'
  brandStrength: 0.5
  lightness: 0.8059384429361671
  saturation: 0.7544255247339606
  rhythmicContrast: 0.8289191683288664
purpose: []
